name: Template sync

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  universal-addon:
    if: github.repository != 'lablabs/terraform-aws-eks-universal-addon'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: lablabs/terraform-aws-eks-universal-addon
          upstream_branch: main
          pr_labels: kind/sync
          pr_branch_name_prefix: "feat/universal-addon-sync"
          pr_title: "feat(sync): sync universal-addon changes"
          pr_commit_msg: "feat(sync): sync universal-addon changes"
